# Generated by Django 5.2 on 2025-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('MonthlyStudentFees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MonthlyTeacherPays', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MonthlyExpenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('MonthlyProfit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
