# Generated by Django 5.2 on 2025-04-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('tution_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=6500, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ac_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stationary_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('security_fee', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
