# Generated by Django 5.2 on 2025-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='security_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
