# Generated by Django 5.2 on 2025-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_enrolled_alter_studentfee_admission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
