# Generated by Django 5.2 on 2025-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentfee_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('graduated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
