# Generated by Django 5.2 on 2025-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeGeneration',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField(auto_now_add=True)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ac_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stationary_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='studentfee',
            name='lab_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
