# Generated by Django 5.2 on 2025-04-04 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_feegeneration_studentfee_lab_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='security_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
