# Generated by Django 5.2 on 2025-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_admission_fee_student_security_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='misc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='security_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='tution_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
