# Generated by Django 5.2 on 2025-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentfee_description_studentfee_misc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feegeneration',
            name='month',
            field=models.DateField(),
        ),
    ]
