# Generated by Django 5.2 on 2025-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_feegeneration_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scanned_doc',
            field=models.ImageField(blank=True, null=True, upload_to='scanned_docs/'),
        ),
    ]
