# Generated by Django 5.2 on 2025-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_scanned_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
