# Generated by Django 5.2 on 2025-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentfee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scanned_doc',
            field=models.FileField(blank=True, null=True, upload_to='scanned_docs/'),
        ),
    ]
