# Generated by Django 5.2 on 2025-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_scanned_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pending_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='pending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
