# Generated by Django 5.2 on 2025-05-28 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_pending_fee_studentfee_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='tution_fee',
            new_name='tuition_fee',
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
