# Generated by Django 5.2 on 2025-04-04 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate_teachers_pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=20)),
                ('pay', models.IntegerField(default=0)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('enrolled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='teachers_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(auto_now_add=True)),
                ('pay', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
        ),
    ]
