# Generated by Django 5.2 on 2025-04-04 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateTeacherPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=20)),
                ('pay', models.IntegerField(default=0)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('enrolled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('pay', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='generate_teachers_pay',
        ),
        migrations.RemoveField(
            model_name='teachers_pay',
            name='name',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.DeleteModel(
            name='teachers_pay',
        ),
    ]
