# Generated by Django 5.2 on 2025-04-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_generateteacherpay_teacher_teacherpay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_doc',
            field=models.ImageField(blank=True, null=True, upload_to='scanned_docs_teachers/'),
        ),
    ]
