# Generated by Django 5.2 on 2025-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_teacher_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_doc',
            field=models.FileField(blank=True, null=True, upload_to='scanned_docs_teachers/'),
        ),
    ]
